#!/usr/bin/env bash
# Recreate the "package gen does not compile" state: a stale generated.go
# that still references fields deleted from src/dst. The tool must
# regenerate (overwriting this file) while the package is broken.
cat > generated.go <<'GEN'
// Code generated by convert. DO NOT EDIT.
// (STALE — left over from before src/dst fields changed; does not compile.)
package gen

import (
	"context"
	"errors"

	destination "example.com/m/destination"
	source "example.com/m/source"
	"github.com/podhmo/minigo/examples/convert-define/model"
)

// convertSrcUserToDstUser converts source.SrcUser to destination.DstUser.
func convertSrcUserToDstUser(ctx context.Context, ec *model.ErrorCollector, src *source.SrcUser) *destination.DstUser {
	if src == nil {
		return nil
	}
	dst := &destination.DstUser{}
	dst.ID = src.ID
	dst.Name = src.Name
	dst.Legacy = src.LegacyField // LegacyField was deleted from SrcUser — build error
	return dst
}
GEN
